# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'keywords_wizard_base.ui'
#
# Created: Fri Nov 29 12:08:21 2013
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_KeywordsWizardBase(object):
    def setupUi(self, KeywordsWizardBase):
        KeywordsWizardBase.setObjectName(_fromUtf8("KeywordsWizardBase"))
        KeywordsWizardBase.resize(765, 393)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(KeywordsWizardBase.sizePolicy().hasHeightForWidth())
        KeywordsWizardBase.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/inasafe/icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        KeywordsWizardBase.setWindowIcon(icon)
        self.verticalLayout = QtGui.QVBoxLayout(KeywordsWizardBase)
        self.verticalLayout.setContentsMargins(16, 16, 16, 4)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lblMainTitle = QtGui.QLabel(KeywordsWizardBase)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblMainTitle.sizePolicy().hasHeightForWidth())
        self.lblMainTitle.setSizePolicy(sizePolicy)
        self.lblMainTitle.setStyleSheet(_fromUtf8("font: 12pt;"))
        self.lblMainTitle.setObjectName(_fromUtf8("lblMainTitle"))
        self.horizontalLayout.addWidget(self.lblMainTitle)
        self.lblStep = QtGui.QLabel(KeywordsWizardBase)
        self.lblStep.setStyleSheet(_fromUtf8("font: 12pt;"))
        self.lblStep.setObjectName(_fromUtf8("lblStep"))
        self.horizontalLayout.addWidget(self.lblStep)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem)
        self.line = QtGui.QFrame(KeywordsWizardBase)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout.addWidget(self.line)
        spacerItem1 = QtGui.QSpacerItem(20, 10, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout.addItem(spacerItem1)
        self.stackedWidget = QtGui.QStackedWidget(KeywordsWizardBase)
        self.stackedWidget.setStyleSheet(_fromUtf8("font-size:10pt"))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pg1Category = QtGui.QWidget()
        self.pg1Category.setStyleSheet(_fromUtf8(""))
        self.pg1Category.setObjectName(_fromUtf8("pg1Category"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pg1Category)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lblSelectyCategory = QtGui.QLabel(self.pg1Category)
        self.lblSelectyCategory.setStyleSheet(_fromUtf8(""))
        self.lblSelectyCategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectyCategory.setWordWrap(True)
        self.lblSelectyCategory.setObjectName(_fromUtf8("lblSelectyCategory"))
        self.verticalLayout_2.addWidget(self.lblSelectyCategory)
        spacerItem2 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem2)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem3, 0, 0, 1, 1)
        self.radAggregationLayer = QtGui.QRadioButton(self.pg1Category)
        self.radAggregationLayer.setObjectName(_fromUtf8("radAggregationLayer"))
        self.gridLayout_6.addWidget(self.radAggregationLayer, 0, 3, 1, 1)
        self.radHazardLayer = QtGui.QRadioButton(self.pg1Category)
        self.radHazardLayer.setObjectName(_fromUtf8("radHazardLayer"))
        self.gridLayout_6.addWidget(self.radHazardLayer, 0, 1, 1, 1)
        self.radExposureLayer = QtGui.QRadioButton(self.pg1Category)
        self.radExposureLayer.setObjectName(_fromUtf8("radExposureLayer"))
        self.gridLayout_6.addWidget(self.radExposureLayer, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_6)
        spacerItem4 = QtGui.QSpacerItem(20, 113, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.stackedWidget.addWidget(self.pg1Category)
        self.pg2Subcategory = QtGui.QWidget()
        self.pg2Subcategory.setStyleSheet(_fromUtf8(""))
        self.pg2Subcategory.setObjectName(_fromUtf8("pg2Subcategory"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.pg2Subcategory)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.lblSelectSubcategory = QtGui.QLabel(self.pg2Subcategory)
        self.lblSelectSubcategory.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectSubcategory.setWordWrap(True)
        self.lblSelectSubcategory.setObjectName(_fromUtf8("lblSelectSubcategory"))
        self.verticalLayout_3.addWidget(self.lblSelectSubcategory)
        spacerItem5 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.radHazardEarthquake = QtGui.QRadioButton(self.pg2Subcategory)
        self.radHazardEarthquake.setObjectName(_fromUtf8("radHazardEarthquake"))
        self.gridLayout.addWidget(self.radHazardEarthquake, 0, 3, 1, 1)
        self.radHazardTsunami = QtGui.QRadioButton(self.pg2Subcategory)
        self.radHazardTsunami.setObjectName(_fromUtf8("radHazardTsunami"))
        self.gridLayout.addWidget(self.radHazardTsunami, 0, 2, 1, 1)
        self.radExposureBuildingFootprints = QtGui.QRadioButton(self.pg2Subcategory)
        self.radExposureBuildingFootprints.setObjectName(_fromUtf8("radExposureBuildingFootprints"))
        self.gridLayout.addWidget(self.radExposureBuildingFootprints, 2, 3, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem6, 0, 0, 3, 1)
        self.radExposurePopulation = QtGui.QRadioButton(self.pg2Subcategory)
        self.radExposurePopulation.setObjectName(_fromUtf8("radExposurePopulation"))
        self.gridLayout.addWidget(self.radExposurePopulation, 2, 1, 1, 1)
        self.radHazardTephra = QtGui.QRadioButton(self.pg2Subcategory)
        self.radHazardTephra.setObjectName(_fromUtf8("radHazardTephra"))
        self.gridLayout.addWidget(self.radHazardTephra, 1, 1, 1, 1)
        self.radExposureRoads = QtGui.QRadioButton(self.pg2Subcategory)
        self.radExposureRoads.setObjectName(_fromUtf8("radExposureRoads"))
        self.gridLayout.addWidget(self.radExposureRoads, 2, 2, 1, 1)
        self.radHazardVolcano = QtGui.QRadioButton(self.pg2Subcategory)
        self.radHazardVolcano.setObjectName(_fromUtf8("radHazardVolcano"))
        self.gridLayout.addWidget(self.radHazardVolcano, 1, 2, 1, 1)
        self.radHazardFlood = QtGui.QRadioButton(self.pg2Subcategory)
        self.radHazardFlood.setObjectName(_fromUtf8("radHazardFlood"))
        self.gridLayout.addWidget(self.radHazardFlood, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        spacerItem7 = QtGui.QSpacerItem(20, 195, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem7)
        self.stackedWidget.addWidget(self.pg2Subcategory)
        self.pg3Units = QtGui.QWidget()
        self.pg3Units.setObjectName(_fromUtf8("pg3Units"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.pg3Units)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.lblSelectUnit = QtGui.QLabel(self.pg3Units)
        self.lblSelectUnit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectUnit.setWordWrap(True)
        self.lblSelectUnit.setObjectName(_fromUtf8("lblSelectUnit"))
        self.verticalLayout_4.addWidget(self.lblSelectUnit)
        spacerItem8 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_4.addItem(spacerItem8)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 0, 0, 3, 1)
        self.radUnitM = QtGui.QRadioButton(self.pg3Units)
        self.radUnitM.setObjectName(_fromUtf8("radUnitM"))
        self.gridLayout_2.addWidget(self.radUnitM, 0, 1, 1, 1)
        self.radUnitF = QtGui.QRadioButton(self.pg3Units)
        self.radUnitF.setObjectName(_fromUtf8("radUnitF"))
        self.gridLayout_2.addWidget(self.radUnitF, 0, 2, 1, 1)
        self.radUnitWetDry = QtGui.QRadioButton(self.pg3Units)
        self.radUnitWetDry.setObjectName(_fromUtf8("radUnitWetDry"))
        self.gridLayout_2.addWidget(self.radUnitWetDry, 0, 3, 1, 1)
        self.radUnitNo2 = QtGui.QRadioButton(self.pg3Units)
        self.radUnitNo2.setObjectName(_fromUtf8("radUnitNo2"))
        self.gridLayout_2.addWidget(self.radUnitNo2, 2, 2, 1, 1)
        self.radUnitNo = QtGui.QRadioButton(self.pg3Units)
        self.radUnitNo.setObjectName(_fromUtf8("radUnitNo"))
        self.gridLayout_2.addWidget(self.radUnitNo, 1, 2, 1, 1)
        self.radUnitKgpsm = QtGui.QRadioButton(self.pg3Units)
        self.radUnitKgpsm.setObjectName(_fromUtf8("radUnitKgpsm"))
        self.gridLayout_2.addWidget(self.radUnitKgpsm, 2, 1, 1, 1)
        self.radUnitMMI = QtGui.QRadioButton(self.pg3Units)
        self.radUnitMMI.setObjectName(_fromUtf8("radUnitMMI"))
        self.gridLayout_2.addWidget(self.radUnitMMI, 1, 1, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 0, 4, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 1, 4, 1, 1)
        spacerItem12 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 2, 4, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        spacerItem13 = QtGui.QSpacerItem(20, 95, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem13)
        self.stackedWidget.addWidget(self.pg3Units)
        self.pg4Field = QtGui.QWidget()
        self.pg4Field.setObjectName(_fromUtf8("pg4Field"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.pg4Field)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.lblSelectField = QtGui.QLabel(self.pg4Field)
        self.lblSelectField.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectField.setWordWrap(True)
        self.lblSelectField.setObjectName(_fromUtf8("lblSelectField"))
        self.verticalLayout_5.addWidget(self.lblSelectField)
        spacerItem14 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_5.addItem(spacerItem14)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        spacerItem15 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem15, 0, 0, 1, 1)
        self.lblField = QtGui.QLabel(self.pg4Field)
        self.lblField.setObjectName(_fromUtf8("lblField"))
        self.gridLayout_3.addWidget(self.lblField, 0, 1, 1, 1)
        self.cmbField = QtGui.QComboBox(self.pg4Field)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmbField.sizePolicy().hasHeightForWidth())
        self.cmbField.setSizePolicy(sizePolicy)
        self.cmbField.setObjectName(_fromUtf8("cmbField"))
        self.gridLayout_3.addWidget(self.cmbField, 0, 2, 1, 1)
        spacerItem16 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem16, 0, 3, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        spacerItem17 = QtGui.QSpacerItem(20, 78, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem17)
        self.stackedWidget.addWidget(self.pg4Field)
        self.pg5Source = QtGui.QWidget()
        self.pg5Source.setObjectName(_fromUtf8("pg5Source"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pg5Source)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.lblSelectSource = QtGui.QLabel(self.pg5Source)
        self.lblSelectSource.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectSource.setWordWrap(True)
        self.lblSelectSource.setObjectName(_fromUtf8("lblSelectSource"))
        self.verticalLayout_6.addWidget(self.lblSelectSource)
        spacerItem18 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem18)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem19 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem19, 0, 0, 1, 1)
        self.lblSource = QtGui.QLabel(self.pg5Source)
        self.lblSource.setObjectName(_fromUtf8("lblSource"))
        self.gridLayout_4.addWidget(self.lblSource, 0, 1, 1, 1)
        self.leSource = QtGui.QLineEdit(self.pg5Source)
        self.leSource.setObjectName(_fromUtf8("leSource"))
        self.gridLayout_4.addWidget(self.leSource, 0, 2, 1, 1)
        spacerItem20 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem20, 0, 3, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_4)
        spacerItem21 = QtGui.QSpacerItem(20, 166, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem21)
        self.stackedWidget.addWidget(self.pg5Source)
        self.pg6Title = QtGui.QWidget()
        self.pg6Title.setObjectName(_fromUtf8("pg6Title"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.pg6Title)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.lblSelectTitle = QtGui.QLabel(self.pg6Title)
        self.lblSelectTitle.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblSelectTitle.setWordWrap(True)
        self.lblSelectTitle.setObjectName(_fromUtf8("lblSelectTitle"))
        self.verticalLayout_7.addWidget(self.lblSelectTitle)
        spacerItem22 = QtGui.QSpacerItem(20, 32, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.verticalLayout_7.addItem(spacerItem22)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        spacerItem23 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem23, 0, 0, 1, 1)
        self.lblTitle = QtGui.QLabel(self.pg6Title)
        self.lblTitle.setObjectName(_fromUtf8("lblTitle"))
        self.gridLayout_5.addWidget(self.lblTitle, 0, 1, 1, 1)
        self.leTitle = QtGui.QLineEdit(self.pg6Title)
        self.leTitle.setObjectName(_fromUtf8("leTitle"))
        self.gridLayout_5.addWidget(self.leTitle, 0, 2, 1, 1)
        spacerItem24 = QtGui.QSpacerItem(36, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem24, 0, 3, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_5)
        spacerItem25 = QtGui.QSpacerItem(20, 141, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem25)
        self.stackedWidget.addWidget(self.pg6Title)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pbnCancel = QtGui.QPushButton(KeywordsWizardBase)
        self.pbnCancel.setObjectName(_fromUtf8("pbnCancel"))
        self.horizontalLayout_2.addWidget(self.pbnCancel)
        spacerItem26 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem26)
        self.pbnBack = QtGui.QPushButton(KeywordsWizardBase)
        self.pbnBack.setObjectName(_fromUtf8("pbnBack"))
        self.horizontalLayout_2.addWidget(self.pbnBack)
        self.pbnNext = QtGui.QPushButton(KeywordsWizardBase)
        self.pbnNext.setObjectName(_fromUtf8("pbnNext"))
        self.horizontalLayout_2.addWidget(self.pbnNext)
        self.pbnFinish = QtGui.QPushButton(KeywordsWizardBase)
        self.pbnFinish.setObjectName(_fromUtf8("pbnFinish"))
        self.horizontalLayout_2.addWidget(self.pbnFinish)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lblField.setBuddy(self.cmbField)
        self.lblSource.setBuddy(self.leSource)
        self.lblTitle.setBuddy(self.leTitle)

        self.retranslateUi(KeywordsWizardBase)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(KeywordsWizardBase)
        KeywordsWizardBase.setTabOrder(self.radHazardLayer, self.radExposureLayer)
        KeywordsWizardBase.setTabOrder(self.radExposureLayer, self.radAggregationLayer)
        KeywordsWizardBase.setTabOrder(self.radAggregationLayer, self.pbnCancel)
        KeywordsWizardBase.setTabOrder(self.pbnCancel, self.pbnBack)
        KeywordsWizardBase.setTabOrder(self.pbnBack, self.pbnNext)
        KeywordsWizardBase.setTabOrder(self.pbnNext, self.pbnFinish)
        KeywordsWizardBase.setTabOrder(self.pbnFinish, self.radHazardFlood)
        KeywordsWizardBase.setTabOrder(self.radHazardFlood, self.radHazardTsunami)
        KeywordsWizardBase.setTabOrder(self.radHazardTsunami, self.radHazardEarthquake)
        KeywordsWizardBase.setTabOrder(self.radHazardEarthquake, self.radHazardTephra)
        KeywordsWizardBase.setTabOrder(self.radHazardTephra, self.radHazardVolcano)
        KeywordsWizardBase.setTabOrder(self.radHazardVolcano, self.radExposurePopulation)
        KeywordsWizardBase.setTabOrder(self.radExposurePopulation, self.radExposureRoads)
        KeywordsWizardBase.setTabOrder(self.radExposureRoads, self.radExposureBuildingFootprints)
        KeywordsWizardBase.setTabOrder(self.radExposureBuildingFootprints, self.radUnitM)
        KeywordsWizardBase.setTabOrder(self.radUnitM, self.radUnitF)
        KeywordsWizardBase.setTabOrder(self.radUnitF, self.radUnitWetDry)
        KeywordsWizardBase.setTabOrder(self.radUnitWetDry, self.radUnitMMI)
        KeywordsWizardBase.setTabOrder(self.radUnitMMI, self.radUnitNo)
        KeywordsWizardBase.setTabOrder(self.radUnitNo, self.radUnitKgpsm)
        KeywordsWizardBase.setTabOrder(self.radUnitKgpsm, self.radUnitNo2)
        KeywordsWizardBase.setTabOrder(self.radUnitNo2, self.cmbField)
        KeywordsWizardBase.setTabOrder(self.cmbField, self.leSource)
        KeywordsWizardBase.setTabOrder(self.leSource, self.leTitle)

    def retranslateUi(self, KeywordsWizardBase):
        KeywordsWizardBase.setWindowTitle(_translate("KeywordsWizardBase", "InaSAFE - Keywords Creation Wizard", None))
        self.lblMainTitle.setText(_translate("KeywordsWizardBase", "InaSAFE Keywords Creation Wizard...", None))
        self.lblStep.setText(_translate("KeywordsWizardBase", "[placeholder]", None))
        self.lblSelectyCategory.setText(_translate("KeywordsWizardBase", "<html><head/><body><p>By following the simple steps in this wizard, you can assign keywords to your layer. First you need to define the type of your layer. InaSAFE uses three kinds of source layers.</p><p>A <span style=\" font-weight:600;\">hazard layer</span> represents something that will impact the people or infrastructure in area. For example a flood, earth quake, tsunami inundation are all different kinds of hazards.</p><p>An <span style=\" font-weight:600;\">exposure layer</span> represents people, property or infrastructure that may be affected in the event of a flood, earthquake, volcano etc.</p><p>An <span style=\" font-weight:600;\">aggregation layer</span> represents regions you can use to summarize the results by. For example, we might summarise the affected people after a flood according to city districts.</p><p>What kind of layer is this one?</p></body></html>", None))
        self.radAggregationLayer.setText(_translate("KeywordsWizardBase", "Aggregation layer", None))
        self.radHazardLayer.setText(_translate("KeywordsWizardBase", "Hazard layer", None))
        self.radExposureLayer.setText(_translate("KeywordsWizardBase", "Exposure layer", None))
        self.lblSelectSubcategory.setText(_translate("KeywordsWizardBase", "[placeholder]", None))
        self.radHazardEarthquake.setText(_translate("KeywordsWizardBase", "Earthquake", None))
        self.radHazardTsunami.setText(_translate("KeywordsWizardBase", "Tsunami", None))
        self.radExposureBuildingFootprints.setText(_translate("KeywordsWizardBase", "Building footprints", None))
        self.radExposurePopulation.setText(_translate("KeywordsWizardBase", "Population", None))
        self.radHazardTephra.setText(_translate("KeywordsWizardBase", "Tephra", None))
        self.radExposureRoads.setText(_translate("KeywordsWizardBase", "Roads", None))
        self.radHazardVolcano.setText(_translate("KeywordsWizardBase", "Volcano", None))
        self.radHazardFlood.setText(_translate("KeywordsWizardBase", "Flood", None))
        self.lblSelectUnit.setText(_translate("KeywordsWizardBase", "[placeholder]", None))
        self.radUnitM.setText(_translate("KeywordsWizardBase", "meters", None))
        self.radUnitF.setText(_translate("KeywordsWizardBase", "feet", None))
        self.radUnitWetDry.setText(_translate("KeywordsWizardBase", "wet / dry", None))
        self.radUnitNo2.setText(_translate("KeywordsWizardBase", "unknown unit or abstract number", None))
        self.radUnitNo.setText(_translate("KeywordsWizardBase", "unknown unit or abstract number", None))
        self.radUnitKgpsm.setText(_translate("KeywordsWizardBase", "kg/m2", None))
        self.radUnitMMI.setText(_translate("KeywordsWizardBase", "MMI", None))
        self.lblSelectField.setText(_translate("KeywordsWizardBase", "[placeholder]", None))
        self.lblField.setText(_translate("KeywordsWizardBase", "Field", None))
        self.lblSelectSource.setText(_translate("KeywordsWizardBase", "<html><head/><body><p><span style=\" font-family:\'Helvetica,arial,freesans,clean,sans-serif\'; font-size:13px; color:#333333;\">Where does the data come from? You may want to write more or less short comment about its source.</span></p></body></html>", None))
        self.lblSource.setText(_translate("KeywordsWizardBase", "Source", None))
        self.lblSelectTitle.setText(_translate("KeywordsWizardBase", "<html><head/><body><p>What is the title for this dataset? A title provides you with a way to give a dataset a more user friendly name than its filename. The title can include spaces. An example of a good title might be \'A flood in Jakarta\' (for a hazard layer) or \'People living in jakarta\' (for an exposure layer).</p></body></html>", None))
        self.lblTitle.setText(_translate("KeywordsWizardBase", "Title", None))
        self.pbnCancel.setText(_translate("KeywordsWizardBase", "Cancel", None))
        self.pbnBack.setText(_translate("KeywordsWizardBase", "Back", None))
        self.pbnNext.setText(_translate("KeywordsWizardBase", "Next", None))
        self.pbnFinish.setText(_translate("KeywordsWizardBase", "Finish", None))

import resources_rc
